name: MyMembership Caller Workflow

on:
  workflow_dispatch:
    inputs:
      feature:
        description: 'Which feature to deploy'
        required: true
        type: choice
        options:
          - class_schedule
          - class_schedule_improved
          - membership
          - training

jobs:
  class-schedule:
    if: github.event.inputs.feature == 'class_schedule'
    uses: ./.github/workflows/class_schedule.yml

  class-schedule-improved:
    if: github.event.inputs.feature == 'class_schedule_improved'
    uses: ./.github/workflows/class_schedule_improved.yml

  membership:
    if: github.event.inputs.feature == 'membership'
    uses: ./.github/workflows/membership.yml

  training:
    if: github.event.inputs.feature == 'training'
    uses: ./.github/workflows/training.yml
