name: Class Schedule CI/CD

on:
  workflow_call:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: staging
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Devolutions Server
        uses: devolutions-community/dvls-login@main
        with:
          server_url: 'https://52.249.182.1/dvls/dvls'
          app_key: ${{ secrets.DVLS_APP_KEY }}
          app_secret: ${{ secrets.DVLS_APP_SECRET }}

      - name: Get Secret from Devolutions Server
        uses: devolutions-community/dvls-get-secret-entry@main
        with:
          server_url: 'https://52.249.182.1/dvls/dvls'
          token: ${{ secrets.DVLS_TOKEN }}
          vault_name: 'DevOpsSecrets'
          entry_name: 'azure-acr'
          output_variable: 'ACR_PASSWORD'

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.ACR_SERVER }}
          username: ${{ vars.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Build for staging
        run: |
          docker build -t ${{ vars.ACR_SERVER }}/class-schedule:staging .
          docker push ${{ vars.ACR_SERVER }}/class-schedule:staging

      - name: Deploy to staging
        run: |
          echo "Deploying class schedule feature to staging..."
          echo "Running smoke tests against staging deployment..."

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
      - uses: actions/checkout@v4

      - name: Login to Devolutions Server
        uses: devolutions-community/dvls-login@main
        with:
          server_url: 'https://52.249.182.1/dvls/dvls'
          app_key: ${{ secrets.DVLS_APP_KEY }}
          app_secret: ${{ secrets.DVLS_APP_SECRET }}

      - name: Get Secret from Devolutions Server
        uses: devolutions-community/dvls-get-secret-entry@main
        with:
          server_url: 'https://52.249.182.1/dvls/dvls'
          token: ${{ secrets.DVLS_TOKEN }}
          vault_name: 'DevOpsSecrets'
          entry_name: 'azure-acr'
          output_variable: 'ACR_PASSWORD'
      
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.ACR_SERVER }}
          username: ${{ vars.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Build for production
        run: |
          docker build -t ${{ vars.ACR_SERVER }}/class-schedule:production .
          docker push ${{ vars.ACR_SERVER }}/class-schedule:production

      - name: Deploy to production
        run: |
          echo "Deploying class schedule feature to production..."
