name: Code Quality Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main, develop ]

permissions:
  issues: write

jobs:
  lint:
    name: ESLint Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Send to Suggesting Agent
        run: |
          # Send the PR number to our n8n workflow
          curl -f -X POST -H "Content-Type: application/json" \\
          -d '{"pull_request_number":"${{ github.event.pull_request.number }}"}' \\
          https://atalearning.app.n8n.cloud/webhook/webhook-test/ef233235-16bd-4648-9455-2149f11204ac
        if: github.event_name == 'pull_request'
