name: Code Quality Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main, develop ]

jobs:
  lint:
    name: ESLint Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint
        id: eslint
        run: |
          RESULTS=$(npx eslint --format json src/)
          echo "ESLINT_RESULTS=$RESULTS" >> $GITHUB_ENV
          
      - name: Create issues for ESLint violations
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const eslintResults = JSON.parse(process.env.ESLINT_RESULTS);
            
            for (const result of eslintResults) {
              const filePath = result.filePath;
              
              for (const message of result.messages) {
                const title = [LINT]  violation in ;
                const body = 
                **File:** 
                **Line:** 
                **Column:** 
                **Rule:** 
                
                **Description:** 
                \;
                
                await github.rest.issues.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: title,
                  body: body,
                  labels: ['technical-debt'],
                  assignees: [context.payload.pull_request.user.login]
                });
              }
            }
