name: Membership Management Pipeline

on:
    push:
      branches: [ main ]
      paths:
        - 'src/features/membership/**'
    workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run security scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

  build:
    needs: security
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '20.x'
            cache: 'npm'

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Lint
        run: npx eslint 'src/features/membership/**' --max-warnings 0

      - name: Build
        run: npm run build

      - name: Test
        run: npm test -- --coverage --watchAll=false

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to production
        run: |
          echo "Deploying membership feature to production..."
          echo "Environment URL: ${{ vars.APP_URL }}"
