name: Runner Demo
on: [workflow_dispatch]

jobs:
  explore-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Show Runner Environment
        run: |
          echo "🔍 Runner Environment:"
          echo "OS: $(uname -a)"
          echo "Directory: $(pwd)"
          echo "User: $(whoami)"

      - name: List Pre-installed Tools
        run: |
          echo "📦 Some Key Tools:"
          git --version
          node --version
          python3 --version

      - name: Demonstrate Workspace
        run: |
          echo "📂 Creating test files..."
          echo "Hello from runner" > test.txt
          ls -la

      - name: Cleanup Check
        run: |
          cd ..
          echo "🧹 Parent directory after steps:"
          ls -la
